apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: jdbc-sink-customers
  namespace: yugabyte-test
  labels:
    strimzi.io/cluster: kafka-connect
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  tasksMax: 4
  config:
    topics: oracle-cdc-customers
    connection.url: jdbc:postgresql://yb-tservers.yugabyte-test.svc.cluster.local:5433/yugabyte
    connection.user: yugabyte
    connection.password: yugabyte
    dialect.name: PostgreSqlDatabaseDialect
    insert.mode: upsert
    pk.mode: record_key
    pk.fields: id
    table.name.format: customers
    auto.create: true
    auto.evolve: true
    batch.size: 3000
    # Debezium SMT for unwrapping envelope
    transforms: unwrap
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: true
    transforms.unwrap.delete.handling.mode: drop
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: jdbc-sink-orders
  namespace: yugabyte-test
  labels:
    strimzi.io/cluster: kafka-connect
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  tasksMax: 4
  config:
    topics: oracle-cdc-orders
    connection.url: jdbc:postgresql://yb-tservers.yugabyte-test.svc.cluster.local:5433/yugabyte
    connection.user: yugabyte
    connection.password: yugabyte
    dialect.name: PostgreSqlDatabaseDialect
    insert.mode: upsert
    pk.mode: record_key
    pk.fields: id
    table.name.format: orders
    auto.create: true
    auto.evolve: true
    batch.size: 3000
    transforms: unwrap
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: true
    transforms.unwrap.delete.handling.mode: drop
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: jdbc-sink-products
  namespace: yugabyte-test
  labels:
    strimzi.io/cluster: kafka-connect
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  tasksMax: 4
  config:
    topics: db2-cdc-products
    connection.url: jdbc:postgresql://yb-tservers.yugabyte-test.svc.cluster.local:5433/yugabyte
    connection.user: yugabyte
    connection.password: yugabyte
    dialect.name: PostgreSqlDatabaseDialect
    insert.mode: upsert
    pk.mode: record_key
    pk.fields: id
    table.name.format: products
    auto.create: true
    auto.evolve: true
    batch.size: 3000
    transforms: unwrap
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: true
    transforms.unwrap.delete.handling.mode: drop
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: jdbc-sink-inventory
  namespace: yugabyte-test
  labels:
    strimzi.io/cluster: kafka-connect
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  tasksMax: 4
  config:
    topics: db2-cdc-inventory
    connection.url: jdbc:postgresql://yb-tservers.yugabyte-test.svc.cluster.local:5433/yugabyte
    connection.user: yugabyte
    connection.password: yugabyte
    dialect.name: PostgreSqlDatabaseDialect
    insert.mode: upsert
    pk.mode: record_key
    pk.fields: id
    table.name.format: inventory
    auto.create: true
    auto.evolve: true
    batch.size: 3000
    transforms: unwrap
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: true
    transforms.unwrap.delete.handling.mode: drop
