{{- if .Values.nodeExporter.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "yb-benchmark.fullname" . }}-node-exporter
  labels:
    {{- include "yb-benchmark.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-exporter
spec:
  selector:
    matchLabels:
      {{- include "yb-benchmark.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: node-exporter
  template:
    metadata:
      labels:
        {{- include "yb-benchmark.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: node-exporter
        app: node-exporter
    spec:
      hostPID: true
      hostNetwork: true
      containers:
      - name: node-exporter
        image: "{{ .Values.nodeExporter.image.repository }}:{{ .Values.nodeExporter.image.tag }}"
        imagePullPolicy: {{ .Values.nodeExporter.image.pullPolicy }}
        args:
          - "--path.procfs=/host/proc"
          - "--path.sysfs=/host/sys"
          - "--path.rootfs=/host/root"
          - "--collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)"
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: metrics
        resources:
          {{- toYaml .Values.nodeExporter.resources | nindent 10 }}
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: root
          mountPath: /host/root
          mountPropagation: HostToContainer
          readOnly: true
      tolerations:
      - operator: Exists
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: root
        hostPath:
          path: /
{{- end }}
