#!/bin/bash
set -euo pipefail

# Generate values-vm-virsh.yaml for the benchmark chart deployed to kind.
# Reads VM IPs from .vms/vm-ips.env and templates static scrape configs.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

VM_IPS="${PROJECT_ROOT}/.vms/vm-ips.env"
OUTPUT="${PROJECT_ROOT}/charts/yb-benchmark/values-vm-virsh.yaml"

if [ ! -f "$VM_IPS" ]; then
    echo "ERROR: ${VM_IPS} not found. Run: make setup-vm-virsh" >&2
    exit 1
fi

source "$VM_IPS"

# Collect master IPs
MASTER_IPS=()
for var in $(grep "^MASTER_.*_IP=" "$VM_IPS" | sort); do
    MASTER_IPS+=("$(echo "$var" | cut -d= -f2)")
done

if [ ${#MASTER_IPS[@]} -eq 0 ]; then
    echo "ERROR: No MASTER_*_IP entries in ${VM_IPS}" >&2
    exit 1
fi

# Collect tserver IPs
TSERVER_IPS=()
for var in $(grep "^TSERVER_.*_IP=" "$VM_IPS" | sort); do
    TSERVER_IPS+=("$(echo "$var" | cut -d= -f2)")
done

if [ ${#TSERVER_IPS[@]} -eq 0 ]; then
    echo "ERROR: No TSERVER_*_IP entries in ${VM_IPS}" >&2
    exit 1
fi

# All VM IPs for node-exporter (masters + tservers, port 9200 per yb-ansible convention)
ALL_IPS=("${MASTER_IPS[@]}" "${TSERVER_IPS[@]}")

# Build targets as YAML flow sequences to avoid heredoc indentation issues
NODE_EXPORTER_TARGETS="["
for i in "${!ALL_IPS[@]}"; do
    [ "$i" -gt 0 ] && NODE_EXPORTER_TARGETS+=", "
    NODE_EXPORTER_TARGETS+="\"${ALL_IPS[$i]}:9200\""
done
NODE_EXPORTER_TARGETS+="]"

TSERVER_TARGETS="["
for i in "${!TSERVER_IPS[@]}"; do
    [ "$i" -gt 0 ] && TSERVER_TARGETS+=", "
    TSERVER_TARGETS+="\"${TSERVER_IPS[$i]}:9000\""
done
TSERVER_TARGETS+="]"

MASTER_TARGETS="["
for i in "${!MASTER_IPS[@]}"; do
    [ "$i" -gt 0 ] && MASTER_TARGETS+=", "
    MASTER_TARGETS+="\"${MASTER_IPS[$i]}:7000\""
done
MASTER_TARGETS+="]"

cat > "$OUTPUT" <<EOF
# Auto-generated by scripts/gen-values-vm-virsh.sh
# YugabyteDB runs on bare-metal VMs (via yb-ansible), benchmark tools on kind.
# VM IPs sourced from .vms/vm-ips.env
#
# Masters:  ${MASTER_IPS[*]}
# TServers: ${TSERVER_IPS[*]}

fullnameOverride: ""

# Sysbench — disabled for vm-virsh (use k6)
sysbench:
  enabled: false

# k6 benchmark — connects to tserver VM over libvirt bridge
k6:
  enabled: true
  image:
    repository: ghcr.io/rophy/containers/k6-sql
    tag: 20260422-69b5ee6
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "2"
      memory: "1Gi"
  replicas: 1
  tables: 10
  tableSize: 100000
  createSecondary: true
  installTrigger: true
  serialCacheSize: 1000
  vus: 4
  warmupTime: 30
  duration: "120s"
  db:
    host: "${TSERVER_IPS[0]}"
    port: "5433"
    user: yugabyte
    password: yugabyte
    name: yugabyte

# Prometheus — scrapes VM targets via static configs
prometheus:
  enabled: true
  image:
    repository: docker.io/prom/prometheus
    tag: v2.48.0
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  retention: 7d

# Node exporter — disabled (runs on VMs via yb-ansible)
nodeExporter:
  enabled: false

# prom-replay: VictoriaMetrics + MinIO + Grafana + Replay Manager
prom-replay:
  enabled: true
  replayManager:
    image:
      repository: null-ptr-exception/prom-replay/replay-manager
      tag: "20260425-2fdf082"
  victoriametrics:
    retentionPeriod: "30d"
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
    scrapeConfig:
      global:
        scrape_interval: 5s
      scrape_configs:
        - job_name: victoriametrics
          static_configs:
            - targets: ["localhost:8428"]
        - job_name: node-exporter
          static_configs:
            - targets: ${NODE_EXPORTER_TARGETS}
        - job_name: yb-tserver
          metrics_path: /prometheus-metrics
          static_configs:
            - targets: ${TSERVER_TARGETS}
        - job_name: yb-master
          metrics_path: /prometheus-metrics
          static_configs:
            - targets: ${MASTER_TARGETS}
  minio:
    persistence:
      size: 5Gi
    resources:
      requests:
        memory: 256Mi
  grafana:
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    extraVolumes:
      - name: yb-tserver-dashboard
        configMap:
          name: yb-benchmark-yb-tserver
    extraVolumeMounts:
      - name: yb-tserver-dashboard
        mountPath: /var/lib/grafana/dashboards/yb-tserver.json
        subPath: yb-tserver.json
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_role: Viewer
EOF

echo "Generated ${OUTPUT}"
echo "  Masters:  ${MASTER_IPS[*]}"
echo "  TServers: ${TSERVER_IPS[*]}"
echo "  k6 host:  ${TSERVER_IPS[0]}:5433"
