#!/bin/bash
set -euo pipefail

# Generate values-vm-virsh.yaml for the benchmark chart deployed to kind.
# Reads VM IPs from .vms/vm-ips.env and templates static scrape configs.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

VM_IPS="${PROJECT_ROOT}/.vms/vm-ips.env"
OUTPUT="${PROJECT_ROOT}/charts/yb-benchmark/values-vm-virsh.yaml"

if [ ! -f "$VM_IPS" ]; then
    echo "ERROR: ${VM_IPS} not found. Run: make setup-vm-virsh" >&2
    exit 1
fi

source "$VM_IPS"

# Collect all tserver IPs
TSERVER_IPS=()
for var in $(grep "^TSERVER_.*_IP=" "$VM_IPS" | sort); do
    TSERVER_IPS+=("$(echo "$var" | cut -d= -f2)")
done

if [ ${#TSERVER_IPS[@]} -eq 0 ]; then
    echo "ERROR: No TSERVER_*_IP entries in ${VM_IPS}" >&2
    exit 1
fi

# All VM IPs for node-exporter (control + tservers, port 9200 per yb-ansible convention)
ALL_IPS=("${CONTROL_IP}")
ALL_IPS+=("${TSERVER_IPS[@]}")

NODE_EXPORTER_TARGETS=""
for ip in "${ALL_IPS[@]}"; do
    NODE_EXPORTER_TARGETS="${NODE_EXPORTER_TARGETS}            - \"${ip}:9200\"\n"
done

TSERVER_TARGETS=""
for ip in "${TSERVER_IPS[@]}"; do
    TSERVER_TARGETS="${TSERVER_TARGETS}            - \"${ip}:9000\"\n"
done

# 3 masters on control VM with distinct ports (7000, 7001, 7002)
MASTER_TARGETS=""
MASTER_TARGETS="${MASTER_TARGETS}            - \"${CONTROL_IP}:7000\"\n"
MASTER_TARGETS="${MASTER_TARGETS}            - \"${CONTROL_IP}:7001\"\n"
MASTER_TARGETS="${MASTER_TARGETS}            - \"${CONTROL_IP}:7002\"\n"

cat > "$OUTPUT" <<EOF
# Auto-generated by scripts/gen-values-vm-virsh.sh
# YugabyteDB runs on bare-metal VMs (via yb-ansible), benchmark tools on kind.
# VM IPs sourced from .vms/vm-ips.env
#
# Control: ${CONTROL_IP}
# TServers: ${TSERVER_IPS[*]}

fullnameOverride: ""

# Sysbench — disabled for vm-virsh (use k6)
sysbench:
  enabled: false

# k6 benchmark — connects to tserver VM over libvirt bridge
k6:
  enabled: true
  image:
    repository: ghcr.io/rophy/containers/k6-sql
    tag: 20260422-69b5ee6
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "2"
      memory: "1Gi"
  replicas: 1
  tables: 10
  tableSize: 100000
  createSecondary: true
  installTrigger: true
  serialCacheSize: 1000
  vus: 4
  warmupTime: 30
  duration: "120s"
  db:
    host: "${TSERVER_IPS[0]}"
    port: "5433"
    user: yugabyte
    password: yugabyte
    name: yugabyte

# Prometheus — scrapes VM targets via static configs
prometheus:
  enabled: true
  image:
    repository: docker.io/prom/prometheus
    tag: v2.48.0
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
  retention: 7d

# Node exporter — disabled (runs on VMs via yb-ansible)
nodeExporter:
  enabled: false

# prom-replay: VictoriaMetrics + MinIO + Grafana + Replay Manager
prom-replay:
  enabled: true
  replayManager:
    image:
      repository: null-ptr-exception/prom-replay/replay-manager
      tag: "20260425-2fdf082"
  victoriametrics:
    retentionPeriod: "30d"
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
    scrapeConfig:
      global:
        scrape_interval: 5s
      scrape_configs:
        - job_name: victoriametrics
          static_configs:
            - targets: ["localhost:8428"]
        - job_name: node-exporter
          static_configs:
            - targets:
$(echo -en "$NODE_EXPORTER_TARGETS")
        - job_name: yb-tserver
          metrics_path: /prometheus-metrics
          static_configs:
            - targets:
$(echo -en "$TSERVER_TARGETS")
        - job_name: yb-master
          metrics_path: /prometheus-metrics
          static_configs:
            - targets:
$(echo -en "$MASTER_TARGETS")
  minio:
    persistence:
      size: 5Gi
    resources:
      requests:
        memory: 256Mi
  grafana:
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    extraVolumes:
      - name: yb-tserver-dashboard
        configMap:
          name: yb-benchmark-yb-tserver
    extraVolumeMounts:
      - name: yb-tserver-dashboard
        mountPath: /var/lib/grafana/dashboards/yb-tserver.json
        subPath: yb-tserver.json
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_role: Viewer
EOF

echo "Generated ${OUTPUT}"
echo "  Control:  ${CONTROL_IP}"
echo "  TServers: ${TSERVER_IPS[*]}"
echo "  k6 host:  ${TSERVER_IPS[0]}:5433"
