- name: Install podman on all VMs
  hosts: all
  roles:
    - podman

- name: Install node-exporter on all VMs
  hosts: all
  roles:
    - node-exporter

- name: Install YugabyteDB
  hosts: yb
  roles:
    - yb-common

- name: Configure and start masters
  hosts: control
  roles:
    - yb-master

- name: Configure and start tservers
  hosts: yb_tservers
  roles:
    - yb-tserver

- name: Install Prometheus
  hosts: control
  roles:
    - prometheus

- name: Install k6
  hosts: control
  roles:
    - bench
